### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by aaashleyyyy** [filveith/BetterDiscord-Spotify-Lyrics-Status#21]
MusixMatch, the thing Spotify uses, has it's own API that I'm pretty sure can do the same thing. Why do you not use it, is it more difficult, or is there some roadblock?

**Comment by aaashleyyyy** [comment]
After some further research, how did you discoverer "textyl.co" there is absolutely zero documentation, and barely any results of the internet for it.

**Comment by filveith** [comment]
Hi, yeah MusixMatch would be perfect, but their API is subscription based. As I want to keep everything free I will not use MusixMatch for the moment.

> After some further research, how did you discoverer "textyl.co" there is absolutely zero documentation, and barely any results of the internet for it.

I found it by chance on a stack overflow question. Yeah, there is absolutely no documentation for it.  We had to 'reverse engineer' the API to be able to use it.
I tried to contact the owner of the API, but I'm still waiting for an answer

**Comment by aaashleyyyy** [comment]
> Hi, yeah MusixMatch would be perfect, but their API is subscription based. As I want to keep everything free I will not use MusixMatch for the moment.
> 
> > After some further research, how did you discoverer "textyl.co" there is absolutely zero documentation, and barely any results of the internet for it.
> 
> I found it by chance on a stack overflow question. Yeah, there is absolutely no documentation for it. We had to 'reverse engineer' the API to be able to use it. I tried to contact the owner of the API, but I'm still waiting for an answer

Well.. The sync'd lyrics are displayed directly in Spotify. Which makes me think there might be a way around it, and instead read the lyrics Spotify is outputting?

**Comment by filveith** [comment]
This was one of our first ideas, to just get the lyrics from Spotify directly.
But there are some issues with that :
- web scrapping is not ideal in this case
- reverse engineering the api that Spotify is using to Display the lyrics would be a lot of work. And I'm sure that you would need a key to use it
- and I don't know how legal it is to use the lyrics that are displayed because Spotify is paying to get them

But if you want to try and develop something using the lyrics from Spotify I would be happy to implement it ;))
